apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hyperdata-system.fullname" . }}
data:
  application-local.yml: |
    server:
      port: 8100
      servlet:
        context-path: /hyperdata
    logging:
      config: classpath:logback-develop.xml
    spring:
      servlet:
        multipart:
          max-file-size: 1TB
          max-request-size: 1TB
      datasource:
        username: hyperdata
        password: tmax
        url: jdbc:tibero:thin:@192.1.3.180:8629:tibero
        driver-class-name: com.tmax.tibero.jdbc.TbDriver
        #    username: sa
        #    password:
        #    url: jdbc:h2:mem:test;INIT=CREATE SCHEMA IF NOT EXISTS HYPERDATA\;CREATE SCHEMA IF NOT EXISTS HYPERDATA_EX\;CREATE SCHEMA IF NOT EXISTS AUTH
        #    driver-class-name: org.h2.Driver
        hikari:
          jdbc-url: ${spring.datasource.url}
          driver-class-name: ${spring.datasource.driver-class-name}
      #rabbitmq
      rabbitmq:
        host: localhost
        port: 5672
        username: guest
        password: guest
      mail:
        host: 127.0.0.1
        port: 587
        properties:
          mail:
            debug: true
            smtp:
              connection-timeout: 5000
              auth: false
              starttls:
                enable: false
              ssl:
                enable: false
      mvc:
        log-request-details: true
        log-resolved-exception: true

      jpa:
        hibernate:
                # ddl-auto: none
          ddl-auto: create
          naming:
            physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
            implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        show-sql: true
        properties:
          hibernate:
            format-sql: true
        database-platform: org.hibernate.dialect.Oracle10gDialect
    #    database-platform: org.hibernate.dialect.H2Dialect
    ##### Hyperdata Module Address Info ############################
    webserver:
      ip: localhost
      port: 8080
    ##### Web Server Config ########################################
    ws:
      default: ${HD_HOME}/
      profiles: ~/tmax/hyperdata/profiles
    ### TIBERO
    tibero:
      ip: localhost
      port: 8629
      username: hyperdata
      password: tmax
      sid: tibero
    ##kubernetes##
    kubernetes:
      config:
        type: kubernetes

    ### keycloak ################
    keycloak:
      enabled: true
      realm: HyperDataRealm
      auth-server-url: http://10.102.187.53:8888/
      ssl-required: none
      resource: HyperDataLogin
      credentials:
        secret: BZJ1u5CcEsHABipiLMP3URG9OlMoIwiI
      use-resource-role-mappings: true
      bearer-only: true
    ### keycloak end ################

    ##ozone##
    ozone:
      config:
        host: 192.1.3.180
        port: 9862
