{{ if .Values.backendSubDir }}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 1024m
spec:
  {{ if .Values.enableHttps }}
  tls:
    - secretName: istio.{{ .Release.Namespace }}-nginx-ingress-nginx
  {{ end }}
  rules:
   -  http:
        paths:
        - path: {{ .Values.backendSubDir }}(/|$)(.*)
          backend:
            serviceName: {{ .Release.Name }}-svc
            servicePort: 5000
   -  http:
        paths:
        - path: {{ .Values.frontendSubDir }}(/|$)(.*)
          backend:
            serviceName: {{ .Release.Name }}-svc
            servicePort: 3000
{{ end }}
