apiVersion: v1
kind: Pod
metadata:
  labels:
    lb: db-dev40
  name: pod-db-hd-dev40
  namespace: hyperdata-dev40
spec:
  containers:
  - env:
    - name: TB_PORT
      value: "8629"
    - name: MAX_SESSION_COUNT
      value: "100"
    - name: TOTAL_SHM_SIZE
      value: "8"
    - name: MEMORY_TARGET
      value: "16"
    - name: LOG_BUFFER
      value: "300M"
    - name: LOG_GROUP
      value: "5"
    - name: LOG_FILE_SIZE
      value: "200M"
    - name: SYSTEM_FILE_SIZE
      value: "1G"
    - name: TEMP_FILE_SIZE
      value: "5G"
    - name: UNDO_FILE_SIZE
      value: "1G"
    - name: USR_FILE_SIZE
      value: "5G"
    - name: DB_CHARACTER_SET
      value: "UTF8"
    - name: LSNR_INVITED_IP
      value: 
    image: 192.168.179.44:5000/hyperdata8.3_tb:20210105_v1 #우리은행배포버전
    name: con-db-hd-dev40
    ports:
    - containerPort: 8629
      name: tb-lsnr
      protocol: TCP
    - containerPort: 8630
      name: tb-sp
      protocol: TCP
    - containerPort: 9999
      name: ora-gw
      protocol: TCP
    - containerPort: 9095
      name: nz-gw
      protocol: TCP
    - containerPort: 9093
      name: iq-gw
      protocol: TCP
    - containerPort: 9091
      name: ase-gw
      protocol: TCP
    - containerPort: 9777
      name: my-gw
      protocol: TCP
    - containerPort: 9097
      name: gp-gw
      protocol: TCP
    resources:
      limits:
        cpu: "4"
        memory: 8Gi
        nvidia.com/gpu: "0"
      requests:
        cpu: "4"
        memory: 8Gi
        nvidia.com/gpu: "0"
    volumeMounts:
    - mountPath: /db
      name: pv-storage
    - name: tz-seoul
      mountPath: /etc/localtime
  securityContext:
    sysctls:
    - name: kernel.sem
      value: 10000 32000 10000 10000
  volumes:
  - name: pv-storage
    persistentVolumeClaim:
      claimName: pvc-db-dev40
  - name: tz-seoul
    hostPath:
      path: /usr/share/zoneinfo/Asia/Seoul
