apiVersion: v1
kind: Pod
metadata:
  labels:
    app: hd-dev40
  name: pod-rm-hd-dev40
  namespace: hyperdata-dev40
spec:
  containers:
  - image: 192.168.179.44:5000/hyperdata8.3_eda:20200626_v1
    imagePullPolicy: IfNotPresent
    name: con-rm-hd-dev40
    ports:
    - containerPort: 5000
      name: rm-port
      protocol: TCP
    resources:
      limits:
        cpu: "2"
        memory: 4Gi
        nvidia.com/gpu: "0"
      requests:
        cpu: "2"
        memory: 4Gi
        nvidia.com/gpu: "0"
    volumeMounts:
    - name: tz-seoul
      mountPath: /etc/localtime
  volumes:
  - name: tz-seoul
    hostPath:
      path: /usr/share/zoneinfo/Asia/Seoul
