apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: hd-dev42
  name: pvc-db-dev42
  namespace: hyperdata-dev42
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 200Gi
  storageClassName: csi-cephfs
  volumeMode: Filesystem
