image: 192.1.1.93:31234/hyperdata_v20.5_tibero/hyperdata_v20.5_be_common:230412_1569442a

# hd version
implementation_version: 20.5.0.6.0
implementation_date: "2023/10/13"
# sql schema version
schema_version: 20.5.0.6.0

hyperdata:
  revision:
    system: "c281b5c4"
    virtualization: "605b8733"
    flow: "9f9bd252"
    visualization: "6dc45930"


db:
  mountPath: /db
  # tibero headless service name
  ip: tiberolocaldns
  port: 8629
  sid: tibero
  persistentVolumeClaimName: tibero-pvc-db