image: 192.1.1.93:31234/hyperdata_v20.5_tibero/hyperdata_v20.5_be_common:230412_1569442a

# hd version
implementation_version: 20.5.0.5.0
implementation_date: "2023/09/04"
# sql schema version
schema_version: 20.5.0.5.0

hyperdata:
  revision:
    system: "8a556b43"
    virtualization: "9f48e6c1"
    flow: "7b7ca124"
    visualization: "a3a1bce7"


db:
  mountPath: /db
  # tibero headless service name
  ip: tiberolocaldns
  persistentVolumeClaimName: tibero-pvc-db