apiVersion: v1
kind: Pod
metadata:
  labels:
    app: mlplatform-mysql
  name: mlplatform-mysql-pod
spec:
  containers:
    - name: mlplatform-mysql-pod
      image: mysql:8.0.29
      imagePullPolicy: "IfNotPresent"
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: {{ .Values.mysql.username }}
        - name: MYSQL_DATABASE
          value: {{ .Values.mysql.database }}
      ports:
        - name: mysql
          containerPort: {{ .Values.mysql.port }}
      resources:
        requests:
          cpu: 2
          memory: 2Gi
        limits:
          cpu: 2
          memory: 2Gi
      volumeMounts:
        - name: data
          mountPath: /var/lib/mysql
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: mlplatform-mysql-pvc
