apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-svc
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-svc
  annotations:
    metallb.universe.tf/allow-shared-ip: top
spec:
  ports:
    - name: backend-port
      port: 5000
      targetPort: 5000
      protocol: TCP
    - name: frontend-port
      port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    app: {{ .Release.Name }}-deployment
  type: LoadBalancer
  sessionAffinity: None
  loadBalancerIP: {{ .Values.loadbalancerAddr }}
  externalTrafficPolicy: Cluster

