#image: 192.1.1.93:31234/hyperdata-ozone-v20.5:1.3.0
image: apache/ozone:1.3.0

#csi:
#  registrar:
#    image: quay.io/k8scsi/csi-node-driver-registrar:v1.0.2
#  provisioner:
#    image: quay.io/k8scsi/csi-provisioner:v1.0.1

om:
  replicas: 1
  resources:
    limits:
      cpu: "0"
      memory: "0"
    requests:
      cpu: "0"
      memory: "0"
  storage:
    size: 10Gi
  service:
    type: NodePort
    # om의 service type이 nodeport일 경우, 아래 nodeport를 사용
    nodePorts:
      om: 31903

scm:
  replicas: 1
  resources:
    limits:
      cpu: "0"
      memory: "0"
    requests:
      cpu: "0"
      memory: "0"
  storage:
    size: 10Gi
  service:
    type: NodePort

datanode:
  replicas: 3
  resources:
    limits:
      cpu: "0"
      memory: "0"
    requests:
      cpu: "0"
      memory: "0"
  storage:
    size: 100Gi

s3g:
  replicas: 1
  resources:
    limits:
      cpu: "0"
      memory: "0"
    requests:
      cpu: "0"
      memory: "0"
  storage:
    size: 10Gi
  service:
    type: NodePort

