image: 192.1.1.93:31234/hyperdata_v20.5_frontend/hyperdata-fe:latest

https:
  enabled: true

proxy:
  bodysize: 1024m
  # minutes
  timeout: 1800

resources:
  requests:
    cpu: 2
    memory: 4Gi
  limits:
    cpu: 2
    memory: 4Gi
customAddon:
  enabled: false
  url: https://192.168.179.40:8080/java
  externalHost: 128.59.105.24
  externalPort: 8090