image: 192.1.1.93:31234/hyperdata_v20.5_frontend/hyperdata-fe:latest

https:
  enabled: true

proxy:
  bodysize: 1024m
  # minutes
  timeout: 1800

resources:
  requests:
    cpu: 2
    memory: 4Gi
  limits:
    cpu: 2
    memory: 4Gi
    
customLogo:
  enabled: false

db:
  mountPath: /db
  persistentVolumeClaimName: tibero-pvc-db

legacy:
  #redirect to
  redirect: https://192.168.179.40:8080