kind: Service
apiVersion: v1
metadata:
  name: lb-db-dev42
  namespace: hyperdata-dev42
  annotations:
    metallb.universe.tf/allow-shared-ip: top
spec:
  ports:
    - name: tb-lsnr
      nodePort: 32010
      port: 8629
      protocol: TCP
      targetPort: 8629
    - name: ora-gw
      nodePort: 32015
      port: 9999
      protocol: TCP
      targetPort: 9999
    - name: nz-gw
      nodePort: 32020
      port: 9095
      protocol: TCP
      targetPort: 9095
    - name: iq-gw
      nodePort: 32025
      port: 9093
      protocol: TCP
      targetPort: 9093
    - name: ase-gw
      nodePort: 32030
      port: 9091
      protocol: TCP
      targetPort: 9091
    - name: my-gw
      nodePort: 32035
      port: 9777
      protocol: TCP
      targetPort: 9777
    - name: gp-gw
      nodePort: 32040
      port: 9097
      protocol: TCP
      targetPort: 9097
  selector:
    lb: db-dev42
  type: LoadBalancer
  sessionAffinity: None
  loadBalancerIP: 192.168.179.42
  externalTrafficPolicy: Cluster
status:
  loadBalancer:
    ingress:
      - ip: 192.168.179.42

