apiVersion: v1
kind: Service
metadata:
  name: hyperdata-flow-svc
  {{ if .Values.loadBalancer.enabled }}
  annotations:
    metallb.universe.tf/allow-shared-ip: top
  {{ end }}
spec:
  ports:
    - name: server-port
      port: {{ .Values.webserver.port }}
      targetPort: {{ .Values.server.port }}
      protocol: TCP
  selector:
    app: hyperdata-flow-deploy
  {{ if .Values.loadBalancer.enabled }}
  type: LoadBalancer
  sessionAffinity: None
  loadBalancerIP: {{ .Values.webserver.ip }}
  externalTrafficPolicy: Cluster
  {{ else }}
  type: NodePort
  {{ end }}

