apiVersion: v1
kind: ConfigMap
metadata:
  name: hyperdata-flow-configmap
data:
  application.yml: |
    svc:
      hyperdata:
        ip: {{ .Values.svc.hyperdata.name }}
        port: {{ .Values.svc.hyperdata.port }}
      proauth:
        ip: {{ .Values.svc.proauth.name }}
        port: {{ .Values.svc.proauth.port }}
      virtualization:
        ip: {{ .Values.svc.virtualization.name }}
        port: {{ .Values.svc.virtualization.port }}
      mlplatform:
        ip: {{ .Values.svc.mlplatform.name }}
        port: {{ .Values.svc.mlplatform.port }}

    ############################ Servlet Config ############################
    server:
      port: {{ .Values.server.port }}
      servlet:
        context-path: {{ .Values.server.servlet.contextPath }}

    ############################ Output Config ############################
    ws:
      filepath: {{ .Values.pvc.mountPath }}/input
      saveoutput_filepath: {{ .Values.pvc.mountPath }}/output
      saveoutput_temp_filepath: {{ .Values.pvc.mountPath }}/temp

    ############################ Tibero Meta/Ex schema Config ############################
    db:
      hyperdata:
        ip: {{ .Values.db.address }}
        port: {{ .Values.db.port }}
        sid: {{ .Values.db.sid }}
        show-sql: {{ .Values.db.show_sql }}
      hyperdata_ex:
        ip: {{ .Values.db.address }}
        port: {{ .Values.db.port }}
        sid: {{ .Values.db.sid }}

    ############################ Connection Pool Config ############################
    db-connection-pool:
      common:
        driver-class-name: com.tmax.tibero.jdbc.TbDriver
        query-timeout: {{ index .Values "db-connection-pool" "common" "query-timeout" }}
        wait-timeout: {{ index .Values "db-connection-pool" "common" "wait-timeout" }}
      hyperdata:
        max-active: {{ index .Values "db-connection-pool" "hyperdata" "max-active" }}
        min-idle: {{ index .Values "db-connection-pool" "hyperdata" "min-idle" }}
        max-idle: {{ index .Values "db-connection-pool" "hyperdata" "max-idle" }}
        idle-timeout: {{ index .Values "db-connection-pool" "hyperdata" "idle-timeout" }}
      hyperdata_ex:
        max-active: {{ index .Values "db-connection-pool" "hyperdata_ex" "max-active" }}
        min-idle: {{ index .Values "db-connection-pool" "hyperdata_ex" "min-idle" }}
        max-idle: {{ index .Values "db-connection-pool" "hyperdata_ex" "max-idle" }}
        idle-timeout: {{ index .Values "db-connection-pool" "hyperdata_ex" "idle-timeout" }}
      hyperdata_editor:
        max-active: {{ index .Values "db-connection-pool" "hyperdata_editor" "max-active" }}
        min-idle: {{ index .Values "db-connection-pool" "hyperdata_editor" "min-idle" }}
        max-idle: {{ index .Values "db-connection-pool" "hyperdata_editor" "max-idle" }}
        idle-timeout: {{ index .Values "db-connection-pool" "hyperdata_editor" "idle-timeout" }}

    ############################ Flow Config ############################
    flow:
      save:
        max-file-row: {{ index .Values "flow" "save" "max-file-row" }}

    ############################ SpringDoc Config ############################
    springdoc:
      version: {{ .Values.springdoc.version }}
      api-docs:
        path: {{ .Values.springdoc.api_docs.path }}
      default-consumes-media-type: {{ .Values.springdoc.default_consumes_media_type }}
      default-produces-media-type: {{ .Values.springdoc.default_produces_media_type }}
      swagger-ui:
        path: {{ .Values.springdoc.swagger_ui.path }}
        operations-sorter: {{ .Values.springdoc.swagger_ui.operations_sorter }}
        tags-sorter: {{ .Values.springdoc.swagger_ui.tags_sorter }}
        disable-swagger-default-url: {{ .Values.springdoc.swagger_ui.disable_swagger_default_url }}
        display-query-params-without-oauth2: {{ .Values.springdoc.swagger_ui.display_query_params_without_oauth2 }}
        doc-expansion: {{ .Values.springdoc.swagger_ui.doc_expansion }}

    ---
    spring.config.activate.on-profile: prod
    logging:
      config: classpath:logback-prod.xml
    ---
    spring.config.activate.on-profile: default
    logging:
      config: classpath:logback-dev.xml
    ---
    spring.config.activate.on-profile: develop
    logging:
      config: classpath:logback-dev.xml

