kind: Service
apiVersion: v1
metadata:
  name: hyperdata-fe-svc-external
spec:
  type: ExternalName
  externalName: {{ .Values.customAddon.externalHost }}
  ports:
    - name: http
      port: {{ .Values.customAddon.externalPort }}
      protocol: TCP
      targetPort: {{ .Values.customAddon.externalPort }}