apiVersion: v1
kind: Service
metadata:
  name: hyperdata-flow-svc
spec:
  ports:
    - name: server-port
      port: {{ .Values.webserver.port }}
      targetPort: {{ .Values.server.port }}
      protocol: TCP
  selector:
    app: hyperdata-flow-deploy
  type: NodePort

