apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hyperdata-system.fullname" . }}
data:
  application.yml: |
    server:
      port: {{ .Values.server.port }}
      servlet:
        contextPath: {{ .Values.server.servlet.contextPath }}
    logging:
      config: {{ .Values.logging.config }}
    spring:
      servlet:
        multipart:
          maxFileSize: {{ .Values.spring.servlet.multipart.maxFileSize }}
          maxRequestSize: {{ .Values.spring.servlet.multipart.maxRequestSize }}
      datasource:
        username: {{ .Values.spring.datasource.username }}
        password: {{ .Values.spring.datasource.password }}
        url: {{ .Values.spring.datasource.url }}
        driverClassName: {{ .Values.spring.datasource.driverClassName }}
        hikari:
          jdbcUrl: {{ .Values.spring.datasource.hikari.jdbcUrl }}
          driverClassName: {{ .Values.spring.datasource.hikari.driverClassName }}
      rabbitmq:
        host: {{ .Values.spring.rabbitmq.host }}
        port: {{ .Values.spring.rabbitmq.port }}
        username: {{ .Values.spring.rabbitmq.username }}
        password: {{ .Values.spring.rabbitmq.password }}
      mail:
        host: {{ .Values.spring.mail.host}}
        port: {{ .Values.spring.mail.port}}
        properties:
          mail:
            debug: {{ .Values.spring.mail.properties.mail.debug}}
            smtp:
              connectionTimeout: {{ .Values.spring.mail.properties.mail.smtp.connectionTimeout}}
              auth: {{ .Values.spring.mail.properties.mail.smtp.auth}}
              starttls:
                enable: {{ .Values.spring.mail.properties.mail.smtp.starttls.enable}}
              ssl:
                enable: {{ .Values.spring.mail.properties.mail.smtp.ssl.enable}}
        username: {{ .Values.spring.mail.username}}
        password: {{ .Values.spring.mail.password}}
      mvc:
        logRequestDetails: {{ .Values.spring.mvc.logRequestDetails}}
        logResolvedException: {{ .Values.spring.mvc.logResolvedException}}

      jpa:
        hibernate:
          naming:
            physicalStrategy: {{ .Values.spring.jpa.hibernate.naming.physicalStrategy}}
            implicitStrategy: {{ .Values.spring.jpa.hibernate.naming.implicitStrategy}}
        showSql: {{ .Values.spring.jpa.showSql}}
        properties:
          hibernate:
            formatSql: {{ .Values.spring.jpa.properties.hibernate.formatSql}}
        databasePlatform: {{ .Values.spring.jpa.databasePlatform}}
    ##### Web Server Config ########################################
    ws:
      default: {{ .Values.ws.default}}
      profiles: {{ .Values.ws.profiles}}
    ### TIBERO
    tibero:
      ip: {{ .Values.tibero.ip}}
      port: {{ .Values.tibero.port}}
      username: {{ .Values.tibero.username}}
      password: {{ .Values.tibero.password}}
      sid: {{ .Values.tibero.sid}}
    ###Kubernetes
    kubernetes:
      config:
        type: kubernetes
      meta:
        name:
          namespace:
            hyperdata:  {{ .Values.kubernetes.meta.name.namespace.hyperdata }}
          rbac:
            cluster-role: {{ .Values.kubernetes.meta.name.rbac.clusterRole}}
            cluster-role-binding: {{ .Values.kubernetes.meta.name.rbac.clusterRoleBinding}}
            service-account: {{ .Values.kubernetes.meta.name.rbac.serviceAccount}}
          pvc:
            ozone: {{ .Values.kubernetes.meta.name.pvc.ozone}}
        replicas: {{ .Values.kubernetes.meta.replicas}}

    ### keycloak ################
    keycloak:
      enabled: {{ .Values.keycloak.enabled}}
      realm: {{ .Values.keycloak.realm}}
      authServerUrl: {{ .Values.keycloak.authServerUrl}}
      sslRequired: {{ .Values.keycloak.sslRequired}}
      resource: {{ .Values.keycloak.resource}}
      credentials:
        secret: {{ .Values.keycloak.credentials.secret}}
      useResourceRoleMappings: {{ .Values.keycloak.useResourceRoleMappings}}
      bearerOnly: {{ .Values.keycloak.bearerOnly}}
    ### keycloak end ################

    ##ozone##
    ozone:
      config:
        host: {{ .Values.ozone.config.host}}
        port: {{ .Values.ozone.config.port}}
